services:
  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    image: superset-nyc-taxi:latest 
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key
    volumes:
      - ./superset:/app/superset_home
    networks:
      - nyc-taxi-airflow_549074_airflow

# required as only include/ is mounted automatically
  scheduler:
    volumes:
      - ./nyc_taxi_dbt:/usr/local/airflow/nyc_taxi_dbt

networks:
  nyc-taxi-airflow_549074_airflow:
    external: true